### PR TITLE
Restore firstInit parameter.

### PR DESCRIPTION
**Pull request by dbezborodovrp**
Related to restoring functionality removed by the rewrite in #2

### CODE REVIEW

**Comment by dbezborodovrp** [comment]
As I mentioned before:

IMHO, `firstInit` isn't really necessary AFAICT.

    $("button#change-class").click(function() {
        $(".wrong-class").addClass('initialize-me');
    }).each(function() {
        console.log(this); // Gives <button>
    });

Is the same as:

    $("button#change-class").click(function() {
        $(".wrong-class").addClass('initialize-me');
    }, function() {
        console.log(this); // Gives <button>
    });

Is my understanding correct? If so, using `.each()` seems clearer to me.

I'll leave the decision to you, off course. :-)

**Comment by dbezborodovrp** [comment]
I deleted a test case that I posted, because it is wrong.

**Comment by dbezborodovrp** [comment]
So, what's the use of `firstInit`?

If you do:

    $(".initialize-me-bold").initialize(function(){
        $(this).css("font-weight", "bold");
    }, function() {
        console.log(this); // Gives Window
    });

Why can't you just do:

    $(".initialize-me-bold").initialize(function(){
        $(this).css("font-weight", "bold");
    });
    console.log(this); // Gives Window

**Comment by adampietrasiak** [comment]
Let's say you've got some modal functionality that need some `.modal-container` at the end of `body`. You want it to be added once and only once. That is use case for first-init.

What you think?

**Pull request closed without merging**
